apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cruise-control
  namespace: myproject
rules:
  - apiGroups:
      - "events.k8s.io" # new events api, used by cluster operator
    resources:
      # The cluster operator needs to be able to create events
      - events
    verbs:
      - create
